/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DockFunnelForm: typeof import('./src/components/forms/DockFunnelForm.vue')['default']
    FieldEditor: typeof import('./src/components/dashboard/sidebar-right/FieldEditor.vue')['default']
    FieldSelectEditor: typeof import('./src/components/dashboard/sidebar-right/FieldEditor/FieldSelectEditor.vue')['default']
    FieldTextEditor: typeof import('./src/components/dashboard/sidebar-right/FieldEditor/FieldTextEditor.vue')['default']
    FormFieldCheckboxList: typeof import('./src/components/forms/FormFields/FormFieldCheckboxList.vue')['default']
    FormFieldSelect: typeof import('./src/components/forms/FormFields/FormFieldSelect.vue')['default']
    FormFieldsRoot: typeof import('./src/components/forms/FormFieldsRoot.vue')['default']
    FormFieldText: typeof import('./src/components/forms/FormFields/FormFieldText.vue')['default']
    FormFlowPreview: typeof import('./src/components/dashboard/preview/FormFlowPreview.vue')['default']
    FormStepPreview: typeof import('./src/components/dashboard/preview/FormStepPreview.vue')['default']
    FormTitle: typeof import('./src/components/dashboard/header/FormTitle.vue')['default']
    StepItem: typeof import('./src/components/dashboard/sidebar-left/StepItem.vue')['default']
  }
}
